[package]
name = "radiothing-qt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soapysdr = "0.3.0"
cpp_core = "0.6.0"
qt_core = "0.5.0"
qt_gui = "0.5.0"
qt_widgets = "0.5.0"
qt_ui_tools = "0.5.0"
syn = "=1.0.57"
serde = "=1.0.118"

# [patch.crates-io]
# qt_macros = {git = "https://github.com/davidedelpapa/ritual.git"}